# Site settings
title: Chris's blog且听风吟 
author: MonsterSlayer
author_avatar: /images/header.jpg
email: alias@domain.tld
description: Stay hungry, stay foolish! 
url: "https://yb2016.github.io"
domain: "http://dongyado.com"
github_username: YB2016
github_site_repo: YB2016/YB2016.github.io
disqus: monsterslayer


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
